name = "netease-music-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "netease-music-proxy"

[env.staging]
name = "netease-music-proxy-staging"

# 环境变量
[vars]
NODE_ENV = "production"

# 路由配置
routes = [
  { pattern = "your-domain.com/api/*", zone_name = "your-domain.com" }
]

# 资源限制
[limits]
cpu_ms = 50000
